
alias clip='xclip -sel clip'
alias bc='bc -l'
alias ..="cd .."
alias wifi="sudo iwlist wlan0 scan |egrep -i SSID\|Address\|Channel\|Quality\|Auth"

# Walk backwards until you hit a "root" folder
function cdr() {

  # for git repos we can make 1 jump
  git_root=`git rev-parse --show-toplevel 2> /dev/null`
  if [ "$git_root" != "" ]
  then
    cd $git_root
    return 0
  fi

  while [ 1 ]
  do
    # Stop at the true root
    if [ "$(pwd)" == "/" ]; then
      break
    fi

    # Stop at the home dir
    # You should have just used cd with no arg :)
    if [ "$(pwd)" == "/home/$USER" ]; then
      break
    fi

    # for subversion < 1.7 thanks to https://gist.github.com/egon1024
    # If this directory contains a .svn directory, but our parent does not,
    # we're at the top of a source tree and we'll call this a "root"
    if [ -d "./.svn" -a ! -d "$(dirname $(pwd))/.svn" ]; then
      return 0
    fi

    if [ $FOUND_ROOT -ne 1 ]
    then
      ROOT_TYPES=("^.svn$")
      for root_type in "${ROOT_TYPES[@]}"
      do
        IS_ROOT=$(ls -a | grep -cP '^.git$')
        if [ "$IS_ROOT" == "1" ]
        then
          return 0
        fi
      done
    fi

    cd ..
  done
}
